name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3   # забираем код из репо

      - name: Setup Arm GNU Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '14.2.Rel1'   # укажите вашу версию
      # теперь arm-none-eabi-* уже в PATH
      - name: Show toolchain
        run: |
          which arm-none-eabi-gcc || true
          arm-none-eabi-gcc --version || true
          which cc
          cc --version

      - name: Sanity checks
        run: |
          echo "CC in Makefile (first):"
          grep -n '^[[:space:]]*CC[[:space:]]*[:?]*=' -n Makefile STM32Make.make || true
          echo "Hardcoded cc usages:"
          grep -nE '(^|[[:space:]])cc([[:space:]]|$)' STM32Make.make || true

      - name: Build project
        run: |
          ./configure.py
          ./build.py
